version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/toyproject/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: /scripts/deploy.sh
      timeout: 1000
      runas: ec2-user