= 토이프로젝트 저장소 API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

== Member-API
=== 로그아웃
operation::logout[snippets='http-request,http-response,request-cookies']

== Article-API
=== 게시글 목록 조회
operation::get-article[snippets='http-request,http-response,query-parameters,response-fields']
=== 게시글 등록
operation::post-article[snippets='http-request,http-response,request-fields,response-fields']
=== 게시글 수정
operation::update-article[snippets='http-request,http-response,request-fields,response-fields']
=== 게시글 삭제
operation::delete-article[snippets='http-request,http-response,path-parameters,response-fields']

== ArticleLike-API
=== 게시글 좋아요 등록
operation::save-like[snippets='http-request,http-response,path-parameters,response-fields']
=== 게시글 좋아요 취소
operation::cancel-like[snippets='http-request,http-response,path-parameters,response-fields']

== Article-Search-API
=== 태그 이름 게시글 검색
operation::article-search[snippets='http-request,http-response,query-parameters,response-fields']

== Token-API
=== AccessToken 재발급
operation::get-new-accessToken[snippets='http-request,http-response,request-cookies,response-cookies']